places=['ireland', 'scotland', 'england', 'belize', 'sweden', 'india']
print(places)
print(sorted(places))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
