friends = ['emily', 'trever', 'leah', 'aaron', 'hubbs', 'g']
print(friends[0].title())
print(friends[1].title())
print(friends[2].title())
print(friends[3].title())
print(friends[4].title())
print(friends[5].title())
print(friends[-1].title())
print(friends[-2].title())
print(friends[-3].title())
print(friends[-4].title())
print(friends[-5].title())
